
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author IstipanyaGrasya
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    private double firstNum;
    private double secondNum;
    private String number;
    private String operator;
    private double answer;
    private double squared;
    private double powered;
    private double squareRoot;

    public calculator() {
        initComponents();

        System.out.println(firstNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        txtEquation = new javax.swing.JTextField();
        txtDisplay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        plusSign = new javax.swing.JButton();
        squareBtn = new javax.swing.JButton();
        minusSign = new javax.swing.JButton();
        multSign = new javax.swing.JButton();
        XYbtn = new javax.swing.JButton();
        divSign = new javax.swing.JButton();
        sqroot = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backspace = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        operan = new javax.swing.JButton();
        log = new javax.swing.JButton();
        cubedBtn = new javax.swing.JButton();

        jButton19.setText("jButton13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(600, 600));

        txtEquation.setEditable(false);
        txtEquation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquationActionPerformed(evt);
            }
        });

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisplayKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(255, 255, 255));
        num2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(255, 255, 255));
        num3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(255, 255, 255));
        num4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(255, 255, 255));
        num5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(255, 255, 255));
        num6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(255, 255, 255));
        num7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(255, 255, 255));
        num8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton3");

        num9.setBackground(new java.awt.Color(255, 255, 255));
        num9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num0.setBackground(new java.awt.Color(255, 255, 255));
        num0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        equalBtn.setBackground(new java.awt.Color(255, 255, 255));
        equalBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        equalBtn.setText("=");
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        plusSign.setBackground(new java.awt.Color(255, 255, 255));
        plusSign.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plusSign.setText("+");
        plusSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusSignActionPerformed(evt);
            }
        });

        squareBtn.setBackground(new java.awt.Color(255, 255, 255));
        squareBtn.setText("X^2");
        squareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareBtnActionPerformed(evt);
            }
        });

        minusSign.setBackground(new java.awt.Color(255, 255, 255));
        minusSign.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        minusSign.setText("-");
        minusSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusSignActionPerformed(evt);
            }
        });

        multSign.setBackground(new java.awt.Color(255, 255, 255));
        multSign.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        multSign.setText("*");
        multSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multSignActionPerformed(evt);
            }
        });

        XYbtn.setBackground(new java.awt.Color(255, 255, 255));
        XYbtn.setText("X^Y");
        XYbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XYbtnActionPerformed(evt);
            }
        });

        divSign.setBackground(new java.awt.Color(255, 255, 255));
        divSign.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divSign.setText("/");
        divSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divSignActionPerformed(evt);
            }
        });

        sqroot.setBackground(new java.awt.Color(255, 255, 255));
        sqroot.setText("sq. rt");
        sqroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrootActionPerformed(evt);
            }
        });

        sin.setBackground(new java.awt.Color(255, 255, 255));
        sin.setText("SIN");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setBackground(new java.awt.Color(255, 255, 255));
        cos.setText("COS");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(255, 255, 255));
        tan.setText("TAN");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        dotBtn.setBackground(new java.awt.Color(255, 255, 255));
        dotBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dotBtn.setText(".");
        dotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel1.setText("My Calculator");

        backspace.setBackground(new java.awt.Color(255, 255, 255));
        backspace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backspace.setText("<--");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        operan.setBackground(new java.awt.Color(255, 255, 255));
        operan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        operan.setText("+/-");
        operan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operanActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(255, 255, 255));
        log.setText("LOG");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        cubedBtn.setBackground(new java.awt.Color(255, 255, 255));
        cubedBtn.setText("X^3");
        cubedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(num9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(multSign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(divSign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(tan)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(log))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cos)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(operan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(minusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(XYbtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cubedBtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(plusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(sqroot)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(squareBtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(backspace))))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEquation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(txtDisplay, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtEquation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sqroot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(squareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(XYbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cubedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(multSign, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(divSign, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(operan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object obj = evt.getSource();
        JButton btn = (JButton) obj;

        // show 1 on display
        String currentVal = txtDisplay.getText();
        txtDisplay.setText(currentVal + btn.getText());

        // add 1 to number string
    }//GEN-LAST:event_jButton1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num9ActionPerformed

    private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBtnActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_dotBtnActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_num0ActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed

        // read the second no.
        secondNum = Double.parseDouble(txtDisplay.getText());

        // perform operation
        switch (operator) {
            case "+":
                answer = firstNum + secondNum;

                txtDisplay.setText(answer + " ");

                break;
            case "-":
                answer = firstNum - secondNum;

                txtDisplay.setText(answer + " ");
                break;
            case "/":
                answer = firstNum / secondNum;

                txtDisplay.setText(answer + " ");
                break;
            case "*":
                answer = firstNum * secondNum;

                txtDisplay.setText(answer + " ");
                break;
        }

        // display operation result
        //txtDisplay.setText(answer + "");
        // append second number to equation
        String eqn = txtEquation.getText();
        txtEquation.setText("=" + eqn + secondNum);


    }//GEN-LAST:event_equalBtnActionPerformed

    private void plusSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusSignActionPerformed

        // System.out.println("First num is: " + txtDisplay.getText());
        if (txtEquation.getText().length() == 0) {
            // get first number
            firstNum = Double.parseDouble(txtDisplay.getText());

            // display it in equation
            txtEquation.setText(firstNum + " +");

            // clear display in txtDisplay
            txtDisplay.setText("");

            // keep track of operation
            operator = "+";
        } else {

            // detect if equation has = sign
            if (txtEquation.getText().indexOf("=") == 0) {

                // make display no. as the first
                firstNum = Double.parseDouble(txtDisplay.getText());

                // update equation display
                txtEquation.setText(firstNum + " +");

                // clear display
                txtDisplay.setText("");

                // note operator
                operator = "+";
            } else if (txtEquation.getText().indexOf("+") != -1) {

                // check if there's a second number
                if (txtDisplay.getText().length() > 0) {

                   // System.out.println("[" + txtDisplay.getText() + "]");
                    // get second number
                    secondNum = Double.parseDouble(txtDisplay.getText());

                    // perform operation
                    answer = firstNum + secondNum;

                    // answer becomes the first number
                    firstNum = answer;

                    // display answer in equation
                    txtEquation.setText(answer + " +");

                    // clear display
                    txtDisplay.setText("");

                } else {
                    // don't replace current operation if it's plus
                    if (!operator.equals("+")) {
                        // extract operator (it's the last char.)
                        String operator = txtEquation.getText().charAt(txtEquation.getText().length() - 1) + "";

                        // change current operator to +
                        txtEquation.setText(txtEquation.getText().replace(operator, "+"));

                        // note the operator
                        this.operator = "+";
                    }

                }

            }

        }


    }//GEN-LAST:event_plusSignActionPerformed

    private void minusSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusSignActionPerformed
       // System.out.println("hello");

        // subtraction
        if (txtEquation.getText().length() == 0) {
            //System.out.println("a");

            // get first number
            firstNum = Double.parseDouble(txtDisplay.getText());

            // display it in equation
            txtEquation.setText(firstNum + " -");

            // clear display in txtDisplay
            txtDisplay.setText("");
            operator = "-";
        } else {
          //  System.out.println("b.1");
            // detect if equation has = sign
            if (txtEquation.getText().indexOf("=") == 0) {
                //System.out.println("b");

                // make display no. as the first
                firstNum = Double.parseDouble(txtDisplay.getText());

                // update equation display
                txtEquation.setText(firstNum + " -");

                // clear display
                txtDisplay.setText("");

                // note operator
                operator = "-";
            } else if (txtEquation.getText().indexOf("-") != -1) {
               // System.out.println("c.1");

                // check if there's a second number
                if (txtDisplay.getText().length() > 0) {
                   // System.out.println("c");

                    //System.out.println(+ txtDisplay.getText());
                    // get second number
                    secondNum = Double.parseDouble(txtDisplay.getText());

                    // perform operation
                    answer = firstNum - secondNum;

                    // answer becomes the first number
                    firstNum = answer;

                    // display answer in equation
                    txtEquation.setText(answer + " -");

                    // clear display
                    txtDisplay.setText("");

                } else {
                    //System.out.println("d.1");

                    // don't replace current operation if it's plus
                    if (!operator.equals("-")) {
                       // System.out.println("d");
                        // extract operator (it's the last char.)
                        String operator = txtEquation.getText().charAt(txtEquation.getText().length() - 1) + "";

                        // change current operator to +
                        txtEquation.setText(txtEquation.getText().replace(operator, "-"));

                        // note the operator
                        this.operator = "-";

                    }
                }
            }
        }
        

    }//GEN-LAST:event_minusSignActionPerformed

    private void divSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divSignActionPerformed
        // division
        if (txtEquation.getText().length() == 0) {
            // get first number
            firstNum = Double.parseDouble(txtDisplay.getText());

            // display it in equation
            txtEquation.setText(firstNum + " /");

            // clear display in txtDisplay
            txtDisplay.setText("");
            operator = "/";
        } else {
            if (txtEquation.getText().indexOf("=") == 0) {

                // make display no. as the first
                firstNum = Double.parseDouble(txtDisplay.getText());

                // update equation display
                txtEquation.setText(firstNum + " -");

                // clear display
                txtDisplay.setText("");

                // note operator
                operator = "-";
            } else if (txtEquation.getText().indexOf("/") != -1) {

                // check if there's a second number
                if (txtDisplay.getText().length() > 0) {

                    //System.out.println(+ txtDisplay.getText());
                    // get second number
                    secondNum = Double.parseDouble(txtDisplay.getText());

                    // perform operation
                    answer = firstNum / secondNum;

                    // answer becomes the first number
                    firstNum = answer;

                    // display answer in equation
                    txtEquation.setText(answer + " /");

                    // clear display
                    txtDisplay.setText("");

                } else {
                    // don't replace current operation if it's plus
                    if (!operator.equals("-")) {
                        // extract operator (it's the last char.)
                        String operator = txtEquation.getText().charAt(txtEquation.getText().length() - 1) + "";

                        // change current operator to +
                        txtEquation.setText(txtEquation.getText().replace(operator, "/"));

                        // note the operator
                        this.operator = "/";

                    }
                }
            }
        }

           
        // jButton1ActionPerformed(evt);
    }//GEN-LAST:event_divSignActionPerformed

    private void multSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multSignActionPerformed
        // multiplication
        if (txtEquation.getText().length() == 0) {
            // get first number
            firstNum = Double.parseDouble(txtDisplay.getText());

            // display it in equation
            txtEquation.setText(firstNum + " * ");

            // clear display in txtDisplay
            txtDisplay.setText("");
            operator = "*";
        } else {
            if (txtEquation.getText().indexOf("=") == 0) {

                // make display no. as the first
                firstNum = Double.parseDouble(txtDisplay.getText());

                // update equation display
                txtEquation.setText(firstNum + " * ");

                // clear display
                txtDisplay.setText("");

                // note operator
                operator = "*";
            }else if (txtEquation.getText().indexOf("/") != -1) {

                // check if there's a second number
                if (txtDisplay.getText().length() > 0) {

                    //System.out.println(+ txtDisplay.getText());
                    // get second number
                    secondNum = Double.parseDouble(txtDisplay.getText());

                    // perform operation
                    answer = firstNum * secondNum;

                    // answer becomes the first number
                    firstNum = answer;

                    // display answer in equation
                    txtEquation.setText(answer + " *");

                    // clear display
                    txtDisplay.setText("");

                } else {
                    // don't replace current operation if it's plus
                    if (!operator.equals("-")) {
                        // extract operator (it's the last char.)
                        String operator = txtEquation.getText().charAt(txtEquation.getText().length() - 1) + "";

                        // change current operator to +
                        txtEquation.setText(txtEquation.getText().replace(operator, "*"));

                        // note the operator
                        this.operator = "*";

                    }
                }
            }

        }
        // jButton1ActionPerformed(evt);
    }//GEN-LAST:event_multSignActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        txtDisplay.setText(txtDisplay.getText().substring(0, txtDisplay.getText().length() - 1));
    }//GEN-LAST:event_backspaceActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        txtDisplay.setText(null);
        txtEquation.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void operanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operanActionPerformed
        double operan = (Double.parseDouble(String.valueOf(txtDisplay.getText())));
        operan = operan * (-1);
        txtDisplay.setText(String.valueOf(operan));
    }//GEN-LAST:event_operanActionPerformed

    private void squareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareBtnActionPerformed
        // raise to 2
        firstNum = Double.parseDouble(txtDisplay.getText());
        squared = firstNum * firstNum;
        txtDisplay.setText(squared + " ");
        txtEquation.setText(firstNum + " ^ 2 ");

    }//GEN-LAST:event_squareBtnActionPerformed

    private void XYbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XYbtnActionPerformed
        // raise to N

        firstNum = Double.parseDouble(txtDisplay.getText());
        secondNum = Double.parseDouble(txtDisplay.getText());

        powered = Math.pow(firstNum, firstNum);
        txtDisplay.setText(powered + " ");
        txtEquation.setText(firstNum + " ^ " + secondNum);


    }//GEN-LAST:event_XYbtnActionPerformed

    private void txtEquationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquationActionPerformed

    }//GEN-LAST:event_txtEquationActionPerformed

    private void sqrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrootActionPerformed
        // square root
        firstNum = Double.parseDouble(txtDisplay.getText());

        double squareRoot = Math.sqrt(firstNum);
        txtDisplay.setText(squareRoot + " ");
        txtEquation.setText("sq.rt of: " + firstNum + " =  ");
    }//GEN-LAST:event_sqrootActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // SINE
        firstNum = Double.parseDouble(txtDisplay.getText());
        double degrees = firstNum;
        double radians = Math.toRadians(firstNum);
        double sine = Math.sin(radians);
        txtDisplay.setText(sine + " ");
        txtEquation.setText("Sine of : " + firstNum + " = ");


    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // COSINE

        firstNum = Double.parseDouble(txtDisplay.getText());
        double degrees = firstNum;
        double radians = Math.toRadians(firstNum);
        double cosine = Math.cos(radians);
        txtDisplay.setText(cosine + " ");
        txtEquation.setText("Cosine of : " + firstNum + " = ");

    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // Tangent

        firstNum = Double.parseDouble(txtDisplay.getText());
        double degrees = firstNum;
        double radians = Math.toRadians(firstNum);
        double tangent = Math.tan(radians);
        txtDisplay.setText(tangent + " ");
        txtEquation.setText("Tangent of : " + firstNum + " = ");
    }//GEN-LAST:event_tanActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        //Log 

        firstNum = Double.parseDouble(txtDisplay.getText());
        double log = Math.log(firstNum);
        txtDisplay.setText(log + " ");
        txtEquation.setText("Log of : " + firstNum + " = ");
    }//GEN-LAST:event_logActionPerformed

    private void cubedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubedBtnActionPerformed
        // cuberoot

        firstNum = Double.parseDouble(txtDisplay.getText());
        double cubed = Math.pow(firstNum, 3);
        txtDisplay.setText(cubed + " ");
        txtEquation.setText(firstNum + " ^ 3 ");
    }//GEN-LAST:event_cubedBtnActionPerformed

    private void txtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisplayKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XYbtn;
    private javax.swing.JButton backspace;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton cubedBtn;
    private javax.swing.JButton divSign;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton log;
    private javax.swing.JButton minusSign;
    private javax.swing.JButton multSign;
    private javax.swing.JButton num0;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton operan;
    private javax.swing.JButton plusSign;
    private javax.swing.JButton sin;
    private javax.swing.JButton sqroot;
    private javax.swing.JButton squareBtn;
    private javax.swing.JButton tan;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField txtEquation;
    // End of variables declaration//GEN-END:variables
}
